name: connectapp_mobile
description: Flutter app for apartment community
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  socket_io_client: ^2.0.3+1
  image_picker: ^1.1.2
  lottie: ^3.1.2
  url_launcher: ^6.3.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.2.3

  # Material 3 is default on Flutter 3.7+

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/logo.png"
